# 어떤 작업인지 이름달기

name: 나의 첫 CI

# 언제 실행하는지
on: [push]

# 어떤 작업할지 알려줘!
jobs:
  helloprint:
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello!"
      - run: whoami
      - run: pwd

# 한마디로 - 깃허브야, 컴퓨터 하나 빌려서 운영체제는 리눅스하고 그안에 명령어 실행해줘!
